AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudTrail Watcher

Parameters:
  ResourcesDefaultPrefix:
    Type: String
    AllowedPattern: '[a-z0-9\-]+'
    ConstraintDescription: "Default prefix for resources MUST contain lowercase letters, hyphens, numbers"
    Description: "Prefix for resources related with CloudTrail Watcher"

  SlackWebhookURL:
    Type: String
    Default: "DISABLED"
    AllowedPattern: '^(DISABLED|https://hooks.slack.com/services/[a-zA-Z/0-9]+)$'
    ConstraintDescription: "If you disable Slack notification, set this value DISABLED."
    Description: "Slack Webhook URL (If you don't want to use the feature, set DISABLED)"

  SetMandatoryTag:
    Type: String
    Default: "False"
    Description: "Set mandatory tags when resources are created."

  DisableAutoscalingAlarm:
    Type: String
    Default: "False"
    Description: "Disable alarm for resources created by autoscaling"

Resources:
  WatcherApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:ap-northeast-2:256724228018:applications/cloudtrail-watcher-lambda-layer'
        SemanticVersion: 0.0.11

  WatcherFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Ref ResourcesDefaultPrefix
      Description: "CloudTrail Watcher Function"
      InlineCode: |
        from cloudtrail_watcher.event_handler import handler

        def watcher_handler(event, context):
            return handler(event, context)
      Role: !GetAtt WatcherFunctionRole.Arn
      Timeout: 120
      MemorySize: 512
      Runtime: python3.12
      Handler: index.watcher_handler
      Layers:
        - !GetAtt WatcherApplication.Outputs.WatcherLayerArn
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref WatcherSNSTopic
          SLACK_WEBHOOK_URL: !Ref SlackWebhookURL
          SET_MANDATORY_TAG: !Ref SetMandatoryTag
          DISABLE_AUTOSCALING_ALARM: !Ref DisableAutoscalingAlarm
      Events:
        DetectLogsFromS3:       # AWS::Lambda::Permission resource created automatically by SAM
          Type: S3
          Properties:
            Bucket: !Ref WatcherLogsBucket
            Events: s3:ObjectCreated:*
  
  WatcherLogsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ResourcesDefaultPrefix
      LifecycleConfiguration:
        Rules:
          - Id: DeleteLogAfter1Year
            Status: Enabled
            ExpirationInDays: 365
  
  # Amazon S3 Bucket Policy for CloudTrail:
  # https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html
  WatcherLogsBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WatcherLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: "s3:GetBucketAcl"
            Resource: !GetAtt WatcherLogsBucket.Arn
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: "s3:PutObject"
            Resource: !Sub "${WatcherLogsBucket.Arn}/*"

  WatcherTrail:
    Type: "AWS::CloudTrail::Trail"
    DependsOn: [WatcherLogsBucketPolicy]
    Properties:
      TrailName: !Ref ResourcesDefaultPrefix
      IsLogging: true
      S3BucketName: !Ref WatcherLogsBucket
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EventSelectors:
        - ReadWriteType: WriteOnly
  
  WatcherSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref ResourcesDefaultPrefix
  
  WatcherFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ResourcesDefaultPrefix}-role"
      Description: "Role for CloudTrail Watcher Lambda function"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !GetAtt WatcherApplication.Outputs.WatcherFunctionPolicyArn
      Policies:
        - PolicyName: !Sub "${ResourcesDefaultPrefix}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::${ResourcesDefaultPrefix}/*"
              - Effect: Allow
                Action: "sns:Publish"
                Resource: !Ref WatcherSNSTopic
