name: Create CloudTrail Watcher Lambda Layer

on:
  release:
    types: [published]

jobs:
  build_lambda_layer:
    runs-on: ubuntu-latest
    name: Build Lambda Layer

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build Lambda Layer
        run: |
          cd functions/watcher
          rm -rf __pycache__/ services/__pycache__/
          zip -r $PWD/layer.zip .

      - name: Create Lambda Layer
        run: |
          cd functions/watcher
          aws lambda publish-layer-version --layer-name cloudtrail-watcher-lambda-layer \
                                           --compatible-runtimes "python3.12" \
                                           --zip-file fileb://$PWD/layer.zip
