name: Create CloudTrail Watcher Lambda Layer

on:
  push:
    branches:
      - "main"
  release:
    types: [published]

jobs:
  build_lambda_layer:
    runs-on: ubuntu-latest
    name: Build Lambda Layer

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Build Lambda Layer
        run: |
          pwd
          ls -al
          cd functions/watcher
          rm -rf __pycache__/ services/__pycache__/
          zip -r $PWD/layer.zip .
      - name: Create Lambda Layer
        run: |
          cd functions/watcher
          aws lambda publish-layer-version --layer-name cloudtrail-watch-lambda-layer \
                                           --compatible-runtimes "python3.12" \
                                           --zip-file fileb://$PWD/layer.zip
